version: 2
jobs:
  build:
    working_directory: /go/src/github.com/sallitex/bbft
    docker:
      - image: satellitex/bbft:$CIRCLE_BRANCH
    steps:
      - checkout
      - restore_cache:
          key: bbft-{{ .Branch }}-{{ checksum "glide.lock" }}
          paths:
            - /go/src/github.com/sallitex/bbft/vendor
      - run:
          name: glide install
          command: |
            vendor_dir=/go/src/github.com/sallitex/bbft/vendor
            if [ ! -s $vendor_dir ]; then
              glide up
            fi
      - save_cache:
          key: bbft-{{ .Branch }}-{{ checksum "glide.lock" }}
          paths:
          - /go/src/github.com/sallitex/bbft/vendor
      - run:
          name: protoc
          command: make proto
      - run:
          name: test
          command: make test
      - run:
          name: build
          command: make build
